# Exercise 04. A/B testing

## Connecting to database

In [1]:
import pandas as pd 
import sqlite3

conn = sqlite3.connect('../data/checking-logs.sqlite')

## Creating two dataframes

In [2]:
test_results = pd.read_sql("""
SELECT
    CASE WHEN t.first_commit_ts < t.first_view_ts THEN 'before' ELSE 'after' END AS time,
    AVG((strftime('%s', t.first_commit_ts) - d.deadlines) / 3600.0) AS avg_diff
FROM test t
JOIN deadlines d ON t.labname = d.labs
WHERE t.labname != 'project1'
GROUP BY time
""", conn)

test_results

     time    avg_diff
0   after -103.953446
1  before  -61.156632

In [3]:
control_results = pd.read_sql("""
SELECT
    CASE WHEN c.first_commit_ts < c.first_view_ts THEN 'before' ELSE 'after' END AS time,
    AVG((strftime('%s', c.first_commit_ts) - d.deadlines) / 3600.0) AS avg_diff
FROM control c
JOIN deadlines d ON c.labname = d.labs
WHERE c.labname != 'project1'
GROUP BY time
""", conn)
control_results

     time    avg_diff
0   after -113.232346
1  before  -99.901448

## Closing the connection

In [4]:
conn.close()

## Results

##### (test group) After seeing the newsfeed, students submit ~43 hours earlier on average

##### (control group) Difference is ~13 hours only (small change)